/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZasadyOchranyOsobnichUdajuRouteImport } from './routes/zasady-ochrany-osobnich-udaju'
import { Route as PodminkyUzitiRouteImport } from './routes/podminky-uziti'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ZasadyOchranyOsobnichUdajuRoute =
  ZasadyOchranyOsobnichUdajuRouteImport.update({
    id: '/zasady-ochrany-osobnich-udaju',
    path: '/zasady-ochrany-osobnich-udaju',
    getParentRoute: () => rootRouteImport,
  } as any)
const PodminkyUzitiRoute = PodminkyUzitiRouteImport.update({
  id: '/podminky-uziti',
  path: '/podminky-uziti',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/podminky-uziti': typeof PodminkyUzitiRoute
  '/zasady-ochrany-osobnich-udaju': typeof ZasadyOchranyOsobnichUdajuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/podminky-uziti': typeof PodminkyUzitiRoute
  '/zasady-ochrany-osobnich-udaju': typeof ZasadyOchranyOsobnichUdajuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/podminky-uziti': typeof PodminkyUzitiRoute
  '/zasady-ochrany-osobnich-udaju': typeof ZasadyOchranyOsobnichUdajuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/podminky-uziti'
    | '/zasady-ochrany-osobnich-udaju'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/podminky-uziti' | '/zasady-ochrany-osobnich-udaju'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/podminky-uziti'
    | '/zasady-ochrany-osobnich-udaju'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PodminkyUzitiRoute: typeof PodminkyUzitiRoute
  ZasadyOchranyOsobnichUdajuRoute: typeof ZasadyOchranyOsobnichUdajuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zasady-ochrany-osobnich-udaju': {
      id: '/zasady-ochrany-osobnich-udaju'
      path: '/zasady-ochrany-osobnich-udaju'
      fullPath: '/zasady-ochrany-osobnich-udaju'
      preLoaderRoute: typeof ZasadyOchranyOsobnichUdajuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podminky-uziti': {
      id: '/podminky-uziti'
      path: '/podminky-uziti'
      fullPath: '/podminky-uziti'
      preLoaderRoute: typeof PodminkyUzitiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PodminkyUzitiRoute: PodminkyUzitiRoute,
  ZasadyOchranyOsobnichUdajuRoute: ZasadyOchranyOsobnichUdajuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
