/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OchranaOsobnichUdajuRouteImport } from './routes/ochrana-osobnich-udaju'
import { Route as IndexRouteImport } from './routes/index'

const OchranaOsobnichUdajuRoute = OchranaOsobnichUdajuRouteImport.update({
  id: '/ochrana-osobnich-udaju',
  path: '/ochrana-osobnich-udaju',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ochrana-osobnich-udaju': typeof OchranaOsobnichUdajuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ochrana-osobnich-udaju'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ochrana-osobnich-udaju'
  id: '__root__' | '/' | '/ochrana-osobnich-udaju'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OchranaOsobnichUdajuRoute: typeof OchranaOsobnichUdajuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ochrana-osobnich-udaju': {
      id: '/ochrana-osobnich-udaju'
      path: '/ochrana-osobnich-udaju'
      fullPath: '/ochrana-osobnich-udaju'
      preLoaderRoute: typeof OchranaOsobnichUdajuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OchranaOsobnichUdajuRoute: OchranaOsobnichUdajuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
